nombre_entrante = ("Ibéricos variados")  
precio_entrante = ("7 euros") 
nombre_principal = ("Filete de ternera en su salsa a la reducción PX") 
precio_principal = ("14.50 euros") 
nombre_postre = ("flan casero con nata y bola de helado") 
precio_postre = ("6.80 euros") 

print("Menú del Día Restaurante Gourmet Casa Lázaro") 
print("-- Entrante --") 
print(nombre_entrante) 
print(precio_entrante)
print("-- Plato Principal --") 
print(nombre_principal)
print(precio_principal)
print("-- Postre --") 
print(nombre_postre)
print(precio_postre) 