nombre_pecho1 = ("Press banca banco plano") 
repeticiones_pecho1 = ("4 x 10") 
peso_pecho1 = ("65kg")
nombre_pecho2 = ("Press superior mancuernas")
repeticiones_pecho2 = ("4 x 8-10")
peso_pecho2 = ("28kg")
nombre_pecho3 = ("Cruce poleas altas")
repeticiones_pecho3 = ("4 x 12-15")
peso_pecho3 = ("20kg/16kg")

nombre_triceps1 = ("Extensiones polea alta")
repeticiones_triceps1 = ("4 x 10-12")
peso_triceps1 = ("25kg")
nombre_triceps2 = ("Extensiones tras cabeza alterno")
repeticiones_triceps2 = ("4 x 12-15")
peso_triceps2 = ("10kg")
nombre_triceps3 = ("Press francés")
repeticiones_triceps3 = ("4 x 8-10")
peso_triceps3 = ("17,5kg")

print("Pecho Día 1")

print(nombre_pecho1)
print(repeticiones_pecho1)
print(peso_pecho1)
print(nombre_pecho2)
print(repeticiones_pecho2)
print(peso_pecho2)
print(nombre_pecho3)
print(repeticiones_pecho3)
print(peso_pecho3)

print("Tríceps Día 1")

print(nombre_triceps1)
print(repeticiones_triceps1)
print(peso_triceps1)
print(nombre_triceps2)
print(repeticiones_triceps2)
print(peso_triceps2)
print(nombre_triceps3)
print(repeticiones_triceps3)
print(peso_triceps3)
