nombre_persona1 = ("Nombre: Roberto") 
edad_persona1 = ("Años: 31") 
ciudad_persona1 = ("Ciudad: Salamanca") 
profesion_persona1 = ("Profesión: Agricultor") 
nombre_persona2 = ("Nombre: Amanda") 
edad_persona2 = ("Años: 19") 
ciudad_persona2 = ("Ciudad: Barcelona") 
profesion_persona2 = ("Profesión: Estudiante")

print("Ficha Personal 1") 
print(nombre_persona1) 
print(edad_persona1) 
print(ciudad_persona1)
print(profesion_persona1)

print("Ficha Personal 2")
print(nombre_persona2)
print(edad_persona2)
print(ciudad_persona2)
print(profesion_persona2)